language: scala
scala:
- 2.12.3
jdk:
- oraclejdk8
cache:
  apt: true
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_install:
- export SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"

before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
env:
- LOG_APP_LEVEL=INFO
before_script:
- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key |
  sudo apt-key add -
- echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
- sudo apt-get update
- sudo apt-get install sbt
script:
- sbt ++$TRAVIS_SCALA_VERSION ktlint test
